### ISSUE TITLE
Copyright Mention of the Used Dataset

### ISSUE THREAD

**Issue by tsoukanas** [panagiotisanagnostou/AI-GA#1]
Mention the [ Copyright [yyyy] [name of copyright owner] ] according to the Licence Agreement of the existing corpus https://github.com/panagiotisanagnostou/AI-GA/blob/05918a598540cecfe2ba4e8284ac7c7c066701ab/README.md?plain=1#L9

**Comment by panagiotisanagnostou** [comment]
Thank you for your comment but, I can not find the necessyry relevant information needed about this repository. That is the reason I referenced the entire repo location.
